In [35]:
####################################################################
# Machine Learning Primer - Workshop
# Day 1 - September 2021
####################################################################

from typing import Tuple

import numpy as np

In [43]:
# data structures (no explicit type)

# ints / floats / str
my_int = 10
my_float = 3.14159265359
my_str = "Bahria"

# lists
my_list_ints = [2, 0, 2, 1, 0, 9]
my_list_strs = ["I", "hope", "this", "workshop", "is", "useful"]

# dictionaries
my_dict = {"bahria": 1, "university": 2}
my_dict = my_dict = dict(bahria=1, university=2)
my_dict2 = {1: "bahria", 2: "university"}

In [28]:
# printing ...
print(my_int)
print(my_dict)

# C/C++ style formatting printing
print(f"The value of pi: {my_float:.2f}.\nWe are at {my_str}")

10
{'bahria': 1, 'university': 2}
The value of pi: 3.14.
We are at Bahria


In [29]:
print("for loop over list")
for x in my_list_ints:
    print(x)

print("\nget its index too")
for idx, x in enumerate(my_list_ints):
    print(idx, x)
    
print("\nlist comprehension")
print([x * 10 for x in my_list_ints])

print("\nappend to list")
my_list_ints.append(10)
my_list_ints += [30, 40]
print(my_list_ints)

for loop over list
2
0
2
1
0
9

get its index too
0 2
1 0
2 2
3 1
4 0
5 9

list comprehension
[20, 0, 20, 10, 0, 90]

append to list
[2, 0, 2, 1, 0, 9, 10, 30, 40]


In [33]:
# iterating over dictionaries
for key, value in my_dict2.items():
    print(f"key: {key},  value: {value}")
    
# accessing dictionary
print(my_dict2[2])

key: 1,  value: bahria
key: 2,  value: university
university


In [30]:
# loop for 10 iterations
for idx in range(10):
    print(idx)

0
1
2
3
4
5
6
7
8
9


In [31]:
# a function
def foo(a, b):
    return a + b

# you can also define the function with type-hints
# (this is just to guide the reader)
def foo2(a: int, b: int) -> int:
    return a + b

print(foo2(10, 20))
print(foo2("ahmad", "h"))

# function can return multiple values
def foo3(a: int, b: int) -> Tuple[int, int]:
    return a - b, a * b

print(foo3(10, 20))

# you can explicitly specify arguments
print(foo3(b=30, a=6))

30
ahmadh
(-10, 200)
(-24, 180)


In [42]:
# some numpy

print("1D array (vector)")
array1 = np.array([1, 2, 5, 6])
print(array1)

print("\n2D matrix")
array2 = np.array(
    [
        [1,   2,  5,  6],
        [10, 20, 50, 60],
    ]
)
print(array2)

print("\npoint-wise multiplication")
print(array1 * array1)

print("\nMatrix multiplication")
print(np.matmul(array2, array1))

print("\nMatrix transpose")
print(array2.T)

1D array (vector)
[1 2 5 6]

2D matrix
[[ 1  2  5  6]
 [10 20 50 60]]

point-wise multiplication
[ 1  4 25 36]

Matrix multiplication
[ 66 660]

Matrix transpose
[[ 1 10]
 [ 2 20]
 [ 5 50]
 [ 6 60]]


In [47]:
print("generate random uniform numbers")
print(np.random.uniform(low=0, high=10, size=(2, 3)))

print("\ngenerate random normally distributed numbers")
print(np.random.normal(loc=0, scale=10, size=(2, 4)))

generate random uniform numbers
[[8.71440575 4.74622298 5.61467213]
 [0.08854486 2.49600243 7.15639036]]

generate random normally distributed numbers
[[-17.83126306  12.05792292  17.2952638    1.84914418]
 [  4.35294562  26.65765896   4.99793961  -3.58953506]]
